#!/usr/bin/env bash
#  uses ssh to connect to your server using
#the private key ~/.ssh/school with the user ubuntu

Host 218560-web-01
    HostName 54.150.140.44
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
